/*
Sekyun Oh
CSC 337, Spring 2019
Assignment 3
guessingGame.js

Interacte with HTML user interface based on understanding of JavaScript.
A random number will be generated based on your choosing number for minimum and maximum.
Its default is 1 to 10. When the view is being loaded,
onclick properties of "start" and "guess" button have been set.
Basically, when a user click "start" button, the computer will generate a randon number
between minimum and maximum.
And, the user is going to find a correct number as inserting different values
based on previous processes.
*/
"use strict";
(function() {
   let answer;
   /**
   window.onload = function()
   This is a anonymous function that is called when html file is being loaded
   **/
   window.onload = function() {
      /**
      refresh everthing when start button clicked
      **/
      let startButton = document.getElementById("start");
      startButton.onclick = start;
      /**
      show process when guess button clicked
      **/
      let guessButton = document.getElementById("guess");
      guessButton.onclick = guess;
   };

   /**
   start()
   This function is called when "start" button is clicked.
   Basically, it calculates minimum and maximum to generate a random number between them
   and store the value into global variable "answer".
   When this function is called, the previous values and current guess value will be disappeared
   because clicking "start" button means that a new game is just created.
   **/
   function start() {
      document.getElementById("previous").innerHTML = '';
      document.getElementById('current').value = '';

      let min = Math.ceil(document.getElementById('min').value);
      let max = Math.floor(document.getElementById('max').value);
      answer = Math.floor(Math.random() * (max - min + 1) ) + min;
   }

   /**
   guess()
   This function is called when "guess" buttom is clicked.
   Basically, it compares the value from a user to the value randomly generated by computuer
   and determine if the value from the user is more, less, or equal to the random value.
   User can see a value of comparison to insert a proper value to find the answer.
   If the user finds correct value, this function removes all previous guesses and show
   the "you got it right".
   **/
   function guess(){
      let guess = document.getElementById('current').value;
      let span = document.createElement("span");
      let previous = document.getElementById("previous");

      if(guess < answer){
         span.appendChild(document.createTextNode("more than " + guess));
      }else if(guess > answer){
         span.appendChild(document.createTextNode("less than " + guess));
      }else{
         previous.innerHTML='';
         span.appendChild(document.createTextNode("you got it right!"));
      }
      span.appendChild(document.createElement("br"));
      previous.insertBefore(span, previous.childNodes[0]);
   }
})();
